### ISSUE TITLE
Unable to configure via provisioning due to nested jsonData

### ISSUE THREAD

**Issue by Xaroth** [fetzerch/grafana-sunandmoon-datasource#11]
as per https://github.com/grafana/grafana/issues/11537 , since this datasource uses a nested jsonData scheme (position.latitude, position.longitude), it is not possible to configure this via the provisioning mechanics ( http://docs.grafana.org/administration/provisioning/ ).

Would it be possible to 'work around' this by allowing jsonData.latitude and jsonData.longitude to alias to jsonData.position.latitude and jsonData.position.longitude, respectively?

**Comment by fetzerch** [comment]
See further discussion in https://github.com/grafana/grafana/issues/11537#issuecomment-466750394.

**Comment by fetzerch** [comment]
I've 'worked around' the issue in https://github.com/fetzerch/grafana-sunandmoon-datasource/pull/13.
