### ISSUE TITLE
Graph panel drawing issue with "Today sofar"

### ISSUE THREAD

**Issue by andig** [fetzerch/grafana-sunandmoon-datasource#19]
I'm seeing this when time range is "today sofar":

<img width="554" alt="Screenshot 2019-08-25 at 13 29 11" src="https://user-images.githubusercontent.com/184815/63649355-c1820680-c73c-11e9-8d2e-34ab7a85cbe5.png">

The top horizontal line is wrong and disappears in "today" mode. Not sure if this is a Grafana or plugin issue.

**Comment by fetzerch** [comment]
That looks indeed strange. For annotations the plugin just sends one timestamp to Grafana.
Therefore I'm expecting that to be a Grafana issue.

I'll see if I can reproduce it. Which annotation did you configure? What plugin and Grafana versions do you use?

**Comment by andig** [comment]
> Which annotation did you configure? What plugin and Grafana versions do you use?

Grafana 6.3.3, plugin installed using grafana cli and github address. 

Not sure about the annotation question?

**Comment by andig** [comment]
I could repro this once more just now, but could- at the same time- not on another chart:

ok:
<img width="602" alt="Screenshot 2019-08-26 at 10 22 09" src="https://user-images.githubusercontent.com/184815/63676542-77a42980-c7eb-11e9-842a-97f0587d05cb.png">

not ok:
<img width="558" alt="Screenshot 2019-08-26 at 10 21 31" src="https://user-images.githubusercontent.com/184815/63676547-7a068380-c7eb-11e9-9e15-c305bf30aa9f.png">

I'll keep looking and will provide an update when the cause becomes clearer.

OT: Out of curiosity as the two are related: would it be an option to add calculation (or approximation) of PV genrator power to this plugin? Apart from temperature PV generation is basically the intersection of sun's altitude and position across the sky vs. solar module horizontal and vertical orientation. Would be happy to contribute/test.

**Comment by fetzerch** [comment]
> Grafana 6.3.3, plugin installed using grafana cli and github address.

Thanks. Just to be sure that it's not the same issue as in #8: Can you please also list the plugin version? Either through `grafana-cli plugins ls` or `http://MYGRAFANAHOST/plugins/fetzerch-sunandmoon-datasource/`.

> Not sure about the annotation question?

Sorry I missunderstood the issue. Because of the dashed line, I thought it's an annotation, but it's actually the sun altitude.

So far I haven't been able to reproduce it. If you see it again, we could try the snapshot share feature (click on the share button, then on snapshot).

> OT: Out of curiosity as the two are related: would it be an option to add calculation (or approximation) of PV genrator power to this plugin? Apart from temperature PV generation is basically the intersection of sun's altitude and position across the sky vs. solar module horizontal and vertical orientation. Would be happy to contribute/test.

Sure, that totally makes sense. It's just that I don't have a lot of spare time to work on this at the moment. If there is Javascript library (or function) that can do the calculation, it would be fairly easy to integrate that. Please open a dedicated issue for this topic.

**Comment by andig** [comment]
Looks like the current version:

    grafana@6e26020deffb:/usr/share/grafana$ grafana-cli plugins ls
    installed plugins:
    fetzerch-sunandmoon-datasource @ 0.1.5 
    grafana-clock-panel @ 1.0.3 
    andig-darksky-datasource @ 1.0.0 
    grafana-influxdb-flux-datasource @ 5.3.2 
    json @ 1.0.0 
    natel-plotly-panel @ 0.0.6

**Comment by fetzerch** [comment]
The addon just passes datapoints to Grafana. I doubt that the issue is caused by the addon. Have you tried reporting this in https://github.com/grafana/grafana?

**Comment by andig** [comment]
No. Unfortunately I‘ve found Grafana to be very slow on issue response especially since 7.0 and have giveen up using it. I‘ll close this for time being.
