### ISSUE TITLE
Plugin is marked as "unsigned" in Grafana plugin list

### ISSUE THREAD

**Issue by bjoernbg** [fetzerch/grafana-sunandmoon-datasource#27]
Thanks for the great plugin!

Any chance that you could add a `manifest.txt` so that Grafana can verify the plugin on startup and it doesn't show as "unsigned" in the plugin list anymore?

**Comment by fetzerch** [comment]
Sure, unfortunately I havent't found a way yet to create the signature. According to https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/ this is not yet possible for community plugins.

**Comment by fetzerch** [comment]
Meanwhile it is possible: https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/ and I'll take care of it.

**Comment by bjoernbg** [comment]
great, that's really good news 👍 :)

**Comment by fetzerch** [comment]
Fixed with https://github.com/grafana/grafana-plugin-repository/pull/789.
