### ISSUE TITLE
Messed up graphics 

### ISSUE THREAD

**Issue by BertSchel** [fetzerch/grafana-sunandmoon-datasource#29]
EXPECTED: Sun altitude curve to follow values
REALITY: Curve not following values
When doing certain actions view gets back to normal. (Actions for example: settings: transparant slider off and on again, changing timepicker, sometimes refresh works but not always...)
Grafana-version is Grafana v7.1.3 .
In pictures white filled curve is sun altitude, Both metrics are on different axes.
![notok](https://user-images.githubusercontent.com/40671217/91472554-ebae5d00-e897-11ea-9d50-f25e43f29803.png)
![ok](https://user-images.githubusercontent.com/40671217/91472565-efda7a80-e897-11ea-98d3-172218624296.png)

**Comment by fetzerch** [comment]
The addon just passes datapoints to Grafana. I doubt that the issue is caused by the addon. Have you tried reporting this in https://github.com/grafana/grafana.

**Comment by BertSchel** [comment]
> The addon just passes datapoints to Grafana. I doubt that the issue is caused by the addon. Have you tried reporting this in https://github.com/grafana/grafana.

Nope, did not report it there yet. Guess you're right that it cannot be caused by the addon, but i never ever had this issue with any other datasources or addons. Will give it a try later in the link you gave me. Thx!

**Comment by Schrolli91** [comment]
Same problem here... And only with this plugin.

@BertSchel have you opened a issue in the grafana repo? Can't find any from you. Do you have found a solution?

**Comment by BertSchel** [comment]
> Same problem here... And only with this plugin.
> Grafana 7.2.2
> 
> ![image](https://user-images.githubusercontent.com/6043382/97982958-d2181d00-1dd4-11eb-9fb9-4c605949e669.png)
> 
> @BertSchel have you opened a issue in the grafana repo? Can't find any from you. Do you have found a solution?

Sorry, I did not open an issue in the grafana repo. For me the issue is currently gone. Here's what I did:
Updated grafana, also 7.2.2, The problem was still there. I made a new dashboard and copy/pasted the graph panels one by one from the old dashboard to the new dashboard. (copy-function from the dropdown menu in the panel: More...→copy) Strangely the graphs seem to be working well now without the unwanted lines.

**Comment by BertSchel** [comment]
Schrolli91 opened an issue in the grafana repo, looks like a bug in the addon afterall. 

See: [grafana/grafana/issues/28804](https://github.com/grafana/grafana/issues/28804l)

**Comment by Schrolli91** [comment]
@fetzerch it looks realy like a bug in the datasource plugin.

Take a look at this. It's using wrong values for the calculation but the raw data gauge is correct.
![image](https://user-images.githubusercontent.com/6043382/98359263-37b01780-2028-11eb-8518-a54ec32a9c3e.png)

**Comment by Schrolli91** [comment]
I think the problem is, that sometimes, there are missing values and these are not filled with `previous`.
And in this case the calculations will be wrong.
It wont help, if i select `Last (Not Null)` on the gauges, because the result of my calc isn't `null`.
In conclusion it will calc `null - 31` and the result isn't `null` but `-31`.
![image](https://user-images.githubusercontent.com/6043382/98440654-33542f00-20fa-11eb-963b-d4b0a9676af8.png)

**Comment by fetzerch** [comment]
Hm. Ok thanks and sorry. That's really strange. Looking at the code I can't spot what could be causing this.

I've reworked the plugin to be compatible with the new grafana plugin toolkit in https://github.com/fetzerch/grafana-sunandmoon-datasource/pull/32. In that branch I'm also no longer able to reproduce your issue. Maybe you want to try it :-)

**Comment by Schrolli91** [comment]
Thanks for your fast reply.
How can i install the plugin from this branch?

**Comment by fetzerch** [comment]
Until it's released on grafana.com, I suppose the easiest is to fetch the [zip file from github (branch react)](https://github.com/fetzerch/grafana-sunandmoon-datasource/archive/react.zip) and unzip into the grafana plugins directory. See https://grafana.com/docs/grafana/latest/plugins/installation/#install-a-packaged-plugin

**Comment by Schrolli91** [comment]
works like a charm with the react branch - thanks 

but its running only a few minutes till now - i will report later if there was any further problems

**Comment by Schrolli91** [comment]
No problems so far - works nice now - thank you

**Comment by BertSchel** [comment]
Thanks for this, works great!
