### ISSUE TITLE
Overriding the datasource location

### ISSUE THREAD

**Issue by rfc1036** [fetzerch/grafana-sunandmoon-datasource#35]
Feature request: I use this great plugin to enhance the HVAC graphs of our data centers, but since they are located at very different latitudes I need to be able to override the global datasource location at least per dashboard (even better: per panel).

**Comment by fetzerch** [comment]
That's on my list for long time.

Would this work for you:

![grafik](https://user-images.githubusercontent.com/1133994/100255114-6ba19d00-2f43-11eb-856d-604534aecaa3.png)

**Comment by rfc1036** [comment]
I was wondering if it could be possible to use the new generic override mechanism but sure, this would work fine.

**Comment by fetzerch** [comment]
I do know that it's possible to use this for aliases, but i haven't seen anything for dashboard options.
What's still missing in my prototype is that variables can't be entered. I suppose that's useful as well.
