### ISSUE TITLE
Unexpected Error with Grafana v7.3.7

### ISSUE THREAD

**Issue by MikeyMikeDO** [fetzerch/grafana-sunandmoon-datasource#38]
After updating my Grafana Docker und Update to the latest Version of sunandmoon i recognized a problem. The plugins is working but if i click in the menu Datasources on Sun and Moon i got the following Error:

An unexpected error happened
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in div
    in div
    in n
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

I also have an Error in my Panel:

An unexpected error happened
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in div
    in div
    in n
    in t
    in t
    in div
    in div
    in div
    in QueryOperationRow
    in div
    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Ma
    in div
    in an
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

I also tried to deinstall the plugin via cli und reinstall it but got the same behavior.

**Comment by fetzerch** [comment]
@MikeyMikeDO are you able to provide exact steps to reproduce the issue?
I've tried to reproduce it with 7.3.7 and 7.4.0 but it works flawlessly.

**Comment by MikeyMikeDO** [comment]
@fetzerch There no special steps i can reproduce. I only updated the the grafana docker container. Today i updated to grafana 7.4.0 and reinstalled the plugin again because of the same error. Maybe grafana got some problems in their grafana.db after several updates to v7.3.7 ?! Tomorrow i will install a fresh Grafana-Docker with a fresh database.

**Comment by MikeyMikeDO** [comment]
With a fresh installation and new Database the failure is gone.

**Comment by 00willo** [comment]
Just noting here for others, I came across this as well with grafana 7.2.0.
I added the plugin to this container, based on this image, which is a very popular container used by the home assistant community.
```
$ podman image ls |grep grafana
docker.io/philhawthorne/docker-influxdb-grafana  latest    a4c6e3b5287c  6 months ago  752 MB
```
https://github.com/philhawthorne/docker-influxdb-grafana

I haven't yet to see if it's still an issue the latest grafana as well (7.5.4)

**Comment by fetzerch** [comment]
@00willo Is this still an issue? Can you provide logs and steps to reproduce?
