### ISSUE TITLE
where is the grafana dashboard file for the screenshot?

### ISSUE THREAD

**Issue by mischief** [fetzerch/grafana-sunandmoon-datasource#4]
![](https://raw.githubusercontent.com/fetzerch/grafana-sunandmoon-datasource/master/src/img/screenshot.png)

this ^

**Comment by fetzerch** [comment]
I've uploaded the dashboard to [grafana.net](https://grafana.net/dashboards/630).

**Comment by mischief** [comment]
@fetzerch thanks!
