### ISSUE TITLE
Not workin on Grafana V8.0.0

### ISSUE THREAD

**Issue by Rushmed** [fetzerch/grafana-sunandmoon-datasource#44]
CAnt use the datasource at new Grafana version.

**Comment by fetzerch** [comment]
Can you please explain in more detail what is not working and what errors you get?

I've just updated from Grafana 7.5.6 to 8.0.0 and the plugin still works. Setting it up on a new installation seems to work as well.

**Comment by Rushmed** [comment]
The view of configuration --> Data sources
![image](https://user-images.githubusercontent.com/59259796/121392530-c6369f80-c94f-11eb-9d10-9d9f7f678be0.png)
![image](https://user-images.githubusercontent.com/59259796/121392707-ecf4d600-c94f-11eb-83d0-82aefd450d24.png)
Of course data source cant be deleted because of "Missing valid datasource id".

The view of configuration --> Plugins --> Sun and Moon
![image](https://user-images.githubusercontent.com/59259796/121393128-583ea800-c950-11eb-85cb-042059d2a310.png)
Stuck at loading...

**Comment by Rushmed** [comment]
Ok, solved it with removing folder \var\lib\grafana\plugins\fetzerch-sunandmoon-datasource and putting back the plugin folder from [download link](https://grafana.com/api/plugins/fetzerch-sunandmoon-datasource/versions/0.2.1/download).

**Comment by lolax80** [comment]
same issue in my case

**Comment by Rushmed** [comment]
@lolax80 Did you try my solution above?

**Comment by lolax80** [comment]
Yes i did
