### ISSUE TITLE
passing a template variable to the data source would be nice

### ISSUE THREAD

**Issue by dluc** [fetzerch/grafana-sunandmoon-datasource#5]
Currently latitude and longitude are defined at the datasource level, so it's not possible to change them dynamically using user input.
For instance, I'd like to combine this datasource with the worldmap:
- the user selects a location
- a map shows the location (worldmap panel)
- a graph shows daylight information (sunandmoon datasource)

**Comment by fetzerch** [comment]
Valid request. I've started to work making this [panel options](https://github.com/fetzerch/grafana-sunandmoon-datasource/tree/panel-options) some time ago, but got stuck.
See also the discussion here: https://github.com/grafana/grafana-plugin-repository/pull/23#issuecomment-229448755

Right now I don't have too much time for this, and I'd be happy if someone is interested to help.
