### ISSUE TITLE
"couldn't find a query runner that matches supplied arguments"

### ISSUE THREAD

**Issue by pljakobs** [fetzerch/grafana-sunandmoon-datasource#55]
I was hoping to use sunrise and sunset times in my solar energy dashboard to scale the daily graphs to be sunrise-1h to sunset+1hr but when trying to read sunrise and sunset into dashboard variables I get the above error.
I'm no grafana expert by a long shot, but I assume that assigning variables through query is just not implemented in this module?

**Comment by fetzerch** [comment]
Might be related to #50. I'm not sure if non-backend datasources support dashboard variables.

**Comment by fetzerch** [comment]
Duplicate of https://github.com/fetzerch/grafana-sunandmoon-datasource/issues/50
