### ISSUE TITLE
Sunrise and sunset per panel option

### ISSUE THREAD

**Issue by ahpohl** [fetzerch/grafana-sunandmoon-datasource#57]
I use the plugin to display sunrise and sunset on the power day plot generated by a solar plant. Unfortunately the annotations are displayed on all panels of the dashboards messing up monthly and yearly data plots. Is there a way to control the annotations on a per panel basis?

![image](https://github.com/fetzerch/grafana-sunandmoon-datasource/assets/30575522/3a111077-8f90-4855-9c7d-ab1845d94de9)

Currently this looks ugly and I cannot leave it like this (have to disable the sun and moon plugin if I cannot find a solution)

**Comment by fetzerch** [comment]
You can restrict the panels here:

![grafik](https://github.com/fetzerch/grafana-sunandmoon-datasource/assets/1133994/85c7d7ad-7898-49e0-b60c-7320946ca66d)

**Comment by ahpohl** [comment]
That is crazy. I don't have the "Show in" option. I have version 0.3.0 of the plugin installed with grafana 9.5.1 on Arch Linux Arm.

![image](https://github.com/fetzerch/grafana-sunandmoon-datasource/assets/30575522/781ec0d3-354c-46d8-a3c7-cfa6e12f27e4)

**Comment by fetzerch** [comment]
Indeed, it's a feature introduced in Grafana 10 (https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-0/#annotation-filtering, https://github.com/grafana/grafana/pull/66325)

**Comment by ahpohl** [comment]
brilliant. I upgraded to grafana 10.0.3 and now I can choose on which panels the annotations should be shown. Issue solved.
