### ISSUE TITLE
Maximum sun altitude

### ISSUE THREAD

**Issue by twam** [fetzerch/grafana-sunandmoon-datasource#61]
Would it be possible to add a 'maximum sun altitude of the day' as a value?

Background:

I want to plot the daily yields of my PV together with that maximum sun altitude of that day for a complete year. My first idea was to just calculate the max of the provided values for that day, but by default Grafana sets the interval of this plot to 3h – so there might be a good chance to miss the actual maximum value. Also it feels kinda wrong to generate/calculate lots of values (to be sure to have the maximum value in the data) and then just search for the maximum.

If you have a better solution instead of adding another value, I'm open to suggestions.

**Comment by fetzerch** [comment]
Implemented in #62. Merged via #66.
