### ISSUE TITLE
updating to grafana 11 - sun and moon plugin broken.....

### ISSUE THREAD

**Issue by peters77** [fetzerch/grafana-sunandmoon-datasource#63]
Hi,

after udating to Grafana 11 the sun and moon plugin is no longer working. 
Had to downgrade to 10.4.3 to get it working again. 
Could you ave a look on that, urgenty needed plugin for all solar guys who uses grafana to monitor their PV installations! :-) 

Thanks in advance. 

Regards,

Christian

**Comment by frezeen** [comment]
do u found a solution for grafana 11?

**Comment by peters77** [comment]
No, still on the latest 10.x release....! 👎
