### ISSUE TITLE
Glitches in the Moon altitude display

### ISSUE THREAD

**Issue by ati** [fetzerch/grafana-sunandmoon-datasource#8]
There are small spikes in the Moon altitude display, which become visible at the short time scale (less than one day). 
Grafana 4.0.1, S&M 0.1.2
![screenshot 2016-12-16 09 52 13](https://cloud.githubusercontent.com/assets/54352/21254347/c50b0d2e-c375-11e6-9fe8-7f2bfd2e13da.png)

**Comment by fetzerch** [comment]
Probably a rounding error. I'll have a closer look.

**Comment by fetzerch** [comment]
@ati Can you give v0.1.3 a try? It seems that suncalc 1.8.0 fixed the glitches.

**Comment by ati** [comment]
@fetzerch -- sorry for the radio silence, could not test anyway -- this installation of Grafana is inactive.

**Comment by fetzerch** [comment]
No problem, I could reproduce it with the old version and now it seems to be fine.
