### ISSUE TITLE
grafana 4.6.2 - no datasource available

### ISSUE THREAD

**Issue by ozett** [fetzerch/grafana-sunandmoon-datasource#9]
i updated grafana to 4.6.3 on debian jessi
if i follow the install doku, i cannot add sun-and-moon as a datasource

is it a bug? can you check this?

**Comment by fetzerch** [comment]
The addon works fine for me. Can you please share the exact steps you did to install it?

**Comment by ozett** [comment]
in my linux cli-history i did this:

`grafana-cli plugins install fetzerch-sunandmoon-datasource`

i am not sure, but before i updated grafana on my debian from 3.8 ? to 4.6 to get the grafana-cli
i did not notice any errors...

❓ what can i check on the system? are there log? do you need anything?

i can see the plugin within grafana, but cannot activate it as a datasource...

**Comment by ozett** [comment]
🚀 
WOW, i checked just a minute ago again in the dropdown of the datasources ....and
💥  there it is...

does it take this long to get installed? i am puzzled....

**Comment by fetzerch** [comment]
Closing this issue as the problem is resolved.
